# AUTO-GENERATED by scripts/sync_client.py — DO NOT EDIT
# Source of truth: the flopscope core library (src/flopscope/)
# Regenerate: uv run scripts/sync_client.py
"""Custom exceptions and warnings for the flopscope client."""

from __future__ import annotations


class FlopscopeError(Exception):
    """Base exception for all flopscope errors."""


class BudgetExhaustedError(FlopscopeError):
    """Raised when an operation would exceed the FLOP budget."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class TimeExhaustedError(FlopscopeError):
    """Raised when an operation exceeds the wall-clock time limit."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class NoBudgetContextError(FlopscopeError):
    """Raised when a counted operation is called outside a BudgetContext."""

    def __init__(
        self,
        message: str = "No active BudgetContext. Wrap your code in `with flopscope.BudgetContext(...):`.",
    ) -> None:
        super().__init__(message)


class SymmetryError(FlopscopeError):
    """Raised when a claimed tensor symmetry does not hold."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class UnsupportedFunctionError(FlopscopeError):
    """Raised when calling a function not available in the installed NumPy."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class UnsupportedDtypeError(TypeError):
    """An operation resolved to a dtype with no billing rate. Raised when production dtype rates are active and the resolved calculation dtype is outside the supported table (e.g. float128), or when a complex-dtype call reaches an op with no complex billing classification."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class UnsupportedReturnType(FlopscopeError):
    """Raised when an op's result cannot be serialized across the client/server boundary."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class UnauthorizedControlError(FlopscopeError):
    """Raised when a session-lifecycle op (budget_open/budget_close) is sent without the trusted control token. Session lifecycle is grader-controlled; participant code cannot open, close, or reset a budget."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class RemoteCallbackError(FlopscopeError):
    """Raised when a callback-taking op (e.g. apply_along_axis) is invoked on the client/server backend, which cannot execute Python callbacks remotely."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class RemoteSerializationError(FlopscopeError):
    """Raised when an argument to a remote op cannot be serialized for the client/server backend (e.g. a generator, lambda, or custom object)."""

    def __init__(self, message: str = "") -> None:
        super().__init__(message)


class FlopscopeWarning(UserWarning):
    """Warning issued when flopscope detects potential numerical issues."""


class SymmetryLossWarning(FlopscopeWarning):
    """Warning issued when an operation causes loss of symmetry metadata."""


class CostFallbackWarning(FlopscopeWarning):
    """Warning issued when flopscope skips its symmetry-aware cost adjustment (e.g. ``ufunc.outer`` / ``tensordot`` on a symmetry group whose degree exceeds the per-call Burnside-enumeration threshold). The op runs correctly with the dense cost charged instead. Suppress with ``flops.configure(symmetry_warnings=False)``."""


class RemoteCallbackWarning(FlopscopeWarning):
    """Warning issued when a callback-taking op (e.g. apply_along_axis) is called in-process; it raises RemoteCallbackError on the remote (client/server) backend. Suppress with ``flops.configure(callback_warnings=False)``."""


class ConfigureNoOpWarning(FlopscopeWarning):
    """Warning issued when flops.configure() is called. configure affects the in-process flopscope backend only; it is a no-op on flopscope-client and the evaluation servers, so its settings do not carry into a graded submission."""


class FlopscopeServerError(FlopscopeError):
    """Server-side error that does not map to a more specific exception."""


# ---------------------------------------------------------------------------
# Error map and dispatcher
# ---------------------------------------------------------------------------

_FLOPSCOPE_ERRORS: frozenset[str] = frozenset(
    {
        "BudgetExhaustedError",
        "TimeExhaustedError",
        "NoBudgetContextError",
        "SymmetryError",
        "UnsupportedFunctionError",
        "UnsupportedDtypeError",
        "UnsupportedReturnType",
        "UnauthorizedControlError",
        "RemoteCallbackError",
        "RemoteSerializationError",
    }
)

_ERROR_MAP: dict[str, type[Exception]] = {
    "BudgetExhaustedError": BudgetExhaustedError,
    "TimeExhaustedError": TimeExhaustedError,
    "NoBudgetContextError": NoBudgetContextError,
    "SymmetryError": SymmetryError,
    "UnsupportedFunctionError": UnsupportedFunctionError,
    "UnsupportedDtypeError": UnsupportedDtypeError,
    "UnsupportedReturnType": UnsupportedReturnType,
    "UnauthorizedControlError": UnauthorizedControlError,
    "RemoteCallbackError": RemoteCallbackError,
    "RemoteSerializationError": RemoteSerializationError,
    "FlopscopeServerError": FlopscopeServerError,
    "ValueError": ValueError,
    "TypeError": TypeError,
    "KeyError": KeyError,
    "RuntimeError": RuntimeError,
    "InvalidRequestError": FlopscopeServerError,
}


def raise_from_response(error_type: str, message: str) -> None:
    """Map *error_type* string to an exception class and raise it.

    Unknown error types are treated as :class:`FlopscopeServerError`.
    """
    # Ensure message is a str (server may send bytes if it contains non-ASCII)
    if isinstance(message, bytes):
        message = message.decode("utf-8", errors="replace")
    if isinstance(error_type, bytes):
        error_type = error_type.decode("utf-8", errors="replace")

    exc_cls = _ERROR_MAP.get(error_type, FlopscopeServerError)
    if error_type in _FLOPSCOPE_ERRORS:
        raise exc_cls(message=message)
    raise exc_cls(message)
